import type { Metadata } from "next";
import { UserProvider } from '../context/UserContext';
import './globals.css';

export const metadata: Metadata = {
  title: "Aspirity",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <UserProvider>
        <body className="bg-primary-bg">{children}</body>
      </UserProvider>
    </html>
  );
}